---
# tasks file for boot_disk

- name: Join list for workers and masters
  set_fact:
    hosts: "{{ groups['masters'] + groups['workers'] | default([]) }}"
  when: hosts is not defined

- include_tasks: lenovo.yml
  with_items:
    - "{{ hosts }}"
  when: hostvars[item]['vendor'] == 'Lenovo'

- include_tasks: kvm.yml
  with_items:
    - "{{ hosts }}"
  when: hostvars[item]['vendor'] == 'KVM'
