---
- name: Play to populate image_hashes for relevant images
  hosts: localhost
  vars:
    images_to_get_hash_for:
      release:
        image: quay.io/openshift-release-dev/ocp-release
        tag: "{{ release_tag | default(openshift_full_version + '-x86_64') }}"
      controller:
        image: quay.io/ocpmetal/assisted-installer-controller
        tag: "{{ controller_tag | default('latest') }}"
  roles:
    - get_image_hash
  post_tasks:
    - name: Set image hashes in registry_host
      set_fact:
        image_hashes: "{{ image_hashes }}"
      delegate_to: assisted_installer
      delegate_facts: true

- name: Play to install UI for Assisted Installer
  hosts: assisted_installer
  become: yes
  become_user: root
  roles:
    - ai_ui_prep
  vars:
    PULL_SECRET:  "{{ pull_secret }}"
    ASSISTED_INSTALLER_HOST: "{{ ansible_fqdn }}"
    REGISTRY_BASE_URL: "{{ mirror_registry }}"
