---
- name: Create directory to hold the registry files
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: u=rwX,g=rX,o=rX
    recurse: yes
  loop:
    - "{{ http_dir }}"
    - "{{ http_data_dir }}"
  become: true

- name: Setup pod
  block:
    - name: Create httpd container
      containers.podman.podman_pod:
        name: "{{ http_store_pod_name }}"
        publish:
          - 80:8080

    - name: Create httpd container
      containers.podman.podman_container:
        name: "{{ http_store_container_name }}"
        image: "{{ container_image }}"
        pod: "{{ http_store_pod_name }}"
        state: stopped
        volumes:
          - "{{ http_data_dir }}:/var/www/html:z"
      register: container_info
  become: true

- name: Setting facts about container
  set_fact:
    http_store_name: "{{ container_info.container.Name }}"
    http_store_pidfile: "{{ container_info.container.ConmonPidFile }}"

- name: Setup http_store service
  block:
    - name: Copy the systemd service file
      copy:
        content: |
          [Unit]
          Description=Podman http_store.service
          [Service]
          Restart=on-failure
          ExecStart=/usr/bin/podman start {{ http_store_name }}
          ExecStop=/usr/bin/podman stop -t 10 {{ http_store_name }}
          KillMode=none
          Type=forking
          PIDFile={{ http_store_pidfile }}
          [Install]
          WantedBy=default.target
        dest: "/etc/systemd/system/http_store.service"
    - name: Reload systemd service
      systemd:
        daemon_reexec: yes
        scope: system

    - name: Enable http_store.service
      systemd:
        name: http_store
        enabled: yes
        scope: system

    - name: Start http_store.service
      systemd:
        name: http_store
        state: started
        scope: system
  become: true
