---
- name: Install packages
  yum:
    name: "{{ package_list }}"
    state: present
    update_cache: true
    disable_gpg_check: yes
  become: yes
  tags: packages


- name: Clone the Assisted Installer repo
  git:
    repo: https://github.com/openshift/assisted-test-infra.git
    dest: /home/kni/assisted_installer
    force: yes
    clone: yes
