---
- name: Copy PullSecret into /home/kni/assisted_installer/pull_secret.txt
  copy:
    content: "{{ PULL_SECRET }}"
    dest: "/home/kni/assisted_installer/pull_secret.txt"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'
    force: yes


- name: Create full environment via make
  make:
    chdir: /home/kni/assisted_installer/
    target: create_full_environment
  become: true
  environment:
    PULL_SECRET:  "{{ PULL_SECRET | to_json }}"
  tags:
  - install


- name: Stop NetworkManager
  service:
    name: NetworkManager
    state: stopped
  become: true
  tags:
  - install


- name: Run the environment via make
  make:
    chdir: /home/kni/assisted_installer/
    target: run
  environment:
    PULL_SECRET_FILE:  "/home/kni/assisted_installer/pull_secret.txt"
    DEPLOY_TARGET: onprem
    ASSISTED_SERVICE_HOST: "{{ ASSISTED_INSTALLER_HOST }}"
    PUBLIC_CONTAINER_REGISTRIES: quay.io,registry.access.redhat.com,registry.redhat.io
    OPENSHIFT_INSTALL_RELEASE_IMAGE: "{{ assisted_installer_images.release.image }}"
    CONTROLLER_IMAGE: "{{ assisted_installer_images.controller.image }}"
    SKIP_CERT_VERIFICATION: true
  become: true
  tags:
  - install


- name: Start NetworkManager
  service:
    name: NetworkManager
    state: started
  become: true
  tags:
  - install
