---
- name: Setup AI
  block:
    - name: Create directories for assisted-installer
      file:
        path: "{{ item }}"
        mode: "0775"
        state: directory
      with_items:
      - "{{ assisted_installer_dir }}"
      - "{{ assisted_installer_dir }}/data"
      - "{{ assisted_installer_dir }}/coreos_installer_data"

    - name: Create directory for assisted-installer database
      file:
        path: "{{ assisted_installer_dir }}/data/postgresql"
        mode: "0775"
        state: directory
        recurse: true

    - name: Download the rhcos image
      get_url:
        url: "{{ rhcos_image }}"
        dest: "{{ assisted_installer_dir }}/{{ rhcos_image | basename }}"

    - name: Get coreos-installer via podman
      containers.podman.podman_container:
        name: coreos-installer
        rm: true
        detach: false
        volume:
        - "{{ assisted_installer_dir }}/coreos_installer_data/:/data:Z"
        workdir: /data
        entrypoint: /bin/bash
        image: "{{ coreos_installer_image }}"
        command: ["-c", "cp /usr/sbin/coreos-installer /data/coreos-installer"]
        state: started

    - name: Move coreos-installer
      copy:
        src: "{{ assisted_installer_dir }}/coreos_installer_data/coreos-installer"
        dest: "{{ assisted_installer_dir }}/coreos-installer"
        remote_src: true

    - name: Template out assisted-installer files
      template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      with_items:
      - src: onprem-environment.j2
        dest: "{{ assisted_installer_dir }}/onprem-environment"
      - src: nginx-ui.conf
        dest: "{{ assisted_installer_dir }}/nginx-ui.conf"

    - name: Create assisted-service pod
      containers.podman.podman_pod:
        name: assisted-service
        state: started
        ports:
        - 8000:8000
        - 8090:8090
        - 8080:8080

    - name: Create database container in assisted-service pod
      containers.podman.podman_container:
        pod: assisted-service
        env_file: "{{ assisted_installer_dir }}/onprem-environment"
        volume:
        - "{{ assisted_installer_dir }}/data/postgresql:/var/lib/pgsql:Z"
        name: db
        image: "{{ assisted_postgres_image }}"
        state: started

    - name: Create assisted installer GUI container in assisted-service pod
      containers.podman.podman_container:
        pod: assisted-service
        env_file: "{{ assisted_installer_dir }}/onprem-environment"
        volume:
        - "{{ assisted_installer_dir }}/nginx-ui.conf:/opt/bitnami/nginx/conf/server_blocks/nginx.conf:Z"
        name: gui
        image: "{{ assisted_service_gui_image }}"
        state: started

    - name: Create assisted installer service container in assisted-service pod
      containers.podman.podman_container:
        pod: assisted-service
        env_file: "{{ assisted_installer_dir }}/onprem-environment"
        volume:
        - "{{ assisted_installer_dir }}/{{ rhcos_image | basename }}:/data/livecd.iso:Z"
        - "{{ assisted_installer_dir }}/coreos-installer:/data/coreos-installer:Z"
        name: installer
        image: "{{ assisted_service_image }}"
        env:
          PULL_SECRET: "{{ PULL_SECRET }}"
        state: started
  become: True
