---
# file: configure_cluster.yml
- hosts: bastion
  roles:
    - configure_cluster
  vars:
    - secure: False
    - debug: True
    - ASSISTED_INSTALLER_HOST: "{{ hostvars['assisted_installer']['host'] }}"
    - ASSISTED_INSTALLER_PORT: "{{ hostvars['assisted_installer']['port'] }}"
    - CLUSTER_ID: "{{ cluster_id }}"
    - NODEIP_PROJECT_NAME: "son-of-spike"

#### fatal: [kaloom-infra]: FAILED! => {"changed": false, "msg": "This module requires the python 'requests-oauthlib' package. Try `pip install requests-oauthlib`."}

### fatal: [kaloom-infra]: FAILED! => {"changed": false, "error": "No module named 'openshift' "msg": "Failed to import the required Python library (openshift) on infra's Python /usr/libexec/platform-python. Please read the module documentation and install it in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter"}

### fatal: [kaloom-infra]: FAILED! => {"changed": false, "msg": "kubernetes-validate python library is required to validate resources"}
