---
- name: Play to install UI for Assisted Installer
  hosts: bastion
  become: yes
  become_user: root
  roles:
  - ai_ui_prep

  vars:
    PULL_SECRET:  "{{ lookup('file', './pull_secret.txt') }}"
