---
# file: deploy_cluster.yml

- name: Create cluster and generate Assisted Installer Discovery ISO
  hosts: bastion
  gather_facts: False
  roles:
    - create_cluster
    - generate_discovery_iso
  vars:
    - secure: False
    - create: True
    - generate: True
    - download: True
    - disconnected: "{{ use_mirror }}"
    - manifests: True
    - CLUSTER_NAME: "{{ cluster_name }}"
    - CLUSTER_ID: "{{ cluster_id }}"
    - BASE_DNS_DOMAIN: "{{ base_dns_domain }}"
    - ASSISTED_INSTALLER_HOST: "{{ hostvars['assisted_installer']['host'] }}"
    - ASSISTED_INSTALLER_PORT: "{{ hostvars['assisted_installer']['port'] }}"
    - SSH_PUBLIC_KEY: "{{ ssh_public_key }}"
    - PULL_SECRET: "{{ pull_secret }}"
    - CLUSTER_NETWORK_CIDR: "{{ cluster_network_cidr }}"
    - CLUSTER_NETWORK_HOST_PREFIX: "{{ cluster_network_host_prefix }}"
    - SERVICE_NETWORK_CIDR: "{{ service_network_cidr }}"
    - OPENSHIFT_VERSION: "{{ openshift_version }}"
    - VIP_DHCP_ALLOCATION: "{{ vip_dhcp_allocation }}"
    - INGRESS_VIP: "{{ ingress_vip }}"
    - API_VIP: "{{ api_vip }}"
    - MACHINE_NETWORK_CIDR: "{{ machine_network_cidr }}"
    - DOWNLOAD_DEST_FILE: "{{ discovery_iso_name }}"
    - DOWNLOAD_DEST_PATH: "/opt/http_store/data"
    - NTP_SERVER: "{{ ntp_server }}"

# #TODO: Patch the cluster for disconnected installation
# - name:
#   hosts: kaloom-infra
#   gather_facts: False
#   roles:
#     - patch_cluster
#   vars:
#     - secure: False
#     - disconnected: True
#     - manifests: True
#    - ASSISTED_INSTALLER_HOST: "{{ hostvars['assisted_installer']['host'] }}"
#    - ASSISTED_INSTALLER_PORT: "{{ hostvars['assisted_installer']['port'] }}"

# #TODO: Apply manifests before cluster installation
# - name:
#   hosts: kaloom-infra
#   gather_facts: False
#   roles:
#       - patch_cluster
#   vars:
#     - secure: False
#     - manifest: True
#     - manifests:
#        - ran
#        - du
#    - ASSISTED_INSTALLER_HOST: "{{ hostvars['assisted_installer']['host'] }}"
#    - ASSISTED_INSTALLER_PORT: "{{ hostvars['assisted_installer']['port'] }}"

- name: Mounting, Booting the Assisted Installer Discovery ISO
  hosts: masters, workers
  gather_facts: False
  strategy: free
  roles:
    - boot_iso
  vars:
    - debug: False
    - boot_iso_url: "{{ discovery_iso_server }}/{{ discovery_iso_name }}"

- name: Installing the cluster
  hosts: bastion
  gather_facts: False
  roles:
    - install_cluster
  vars:
    - install: True
    - debug: False
    - ASSISTED_INSTALLER_HOST: "{{ hostvars['assisted_installer']['host'] }}"
    - ASSISTED_INSTALLER_PORT: "{{ hostvars['assisted_installer']['port'] }}"
    - CLUSTER_ID: "{{ cluster_id }}"
    - INGRESS_VIP: "{{ ingress_vip }}"
    - API_VIP: "{{ api_vip }}"
    - VIP_DHCP_ALLOCATION: "{{ vip_dhcp_allocation }}"

- name: Monitoring hosts installation
  hosts: masters, workers
  gather_facts: False
  strategy: free
  roles:
    - monitor_host
  vars:
    - debug: True
    - ASSISTED_INSTALLER_HOST: "{{ hostvars['assisted_installer']['host'] }}"
    - ASSISTED_INSTALLER_PORT: "{{ hostvars['assisted_installer']['port'] }}"
    - CLUSTER_ID: "{{ cluster_id }}"

# TODO: once completed grap cluster credentials
- name: Monitoring cluster installation
  hosts: bastion
  gather_facts: False
  roles:
    - monitor_cluster
  vars:
    - debug: True
    - ASSISTED_INSTALLER_HOST: "{{ hostvars['assisted_installer']['host'] }}"
    - ASSISTED_INSTALLER_PORT: "{{ hostvars['assisted_installer']['port'] }}"
    - CLUSTER_ID: "{{ cluster_id }}"


