---
# file: generate_discovery_iso.yml
- hosts: bastion
  roles:
    - generate_discovery_iso
  vars:
    - download: False
    - secure: False
    - generate: True
    - debug: True
    - CLUSTER_ID: "{{ cluster_id }}"
    - CLUSTER_NAME: "{{ cluster_name }}"
    - ASSISTED_INSTALLER_HOST: "{{ hostvars['assisted_installer']['host'] }}"
    - ASSISTED_INSTALLER_PORT: "{{ hostvars['assisted_installer']['port'] }}"
    - DOWNLOAD_DEST_FILE: "{{ discovery_iso_name }}"
    - DOWNLOAD_DEST_PATH: "/opt/http_store/data"
