---
# file: generate_rwn_iso.yml
- hosts: rhpool-infra
  roles:
    - generate_rwn_iso
  vars:
    - download: False
    - secure: False
    - generate: True
    - debug: True
    - ASSISTED_INSTALLER_HOST: "{{ hostvars['assisted_installer']['host'] }}"
    - ASSISTED_INSTALLER_PORT: "{{ hostvars['assisted_installer']['port'] }}"
    - CLUSTER_ID: "{{ cluster_id }}"
    - WORKER_CONFIG_ROLE: "worker"
    - SSH_PUBLIC_KEY: "{{ ssh_public_key }}"
