---
# file: monitor_cluster.yml

- name: Monitoring hosts installation
  hosts: masters, workers
  gather_facts: False
  strategy: free
  roles:
    - monitor_host
  vars:
    - debug: True
    - ASSISTED_INSTALLER_HOST: "{{ hostvars['assisted_installer']['host'] }}"
    - ASSISTED_INSTALLER_PORT: "{{ hostvars['assisted_installer']['port'] }}"
    - CLUSTER_ID: "{{ cluster_id }}"

- name: Monitoring cluster installation
  hosts: bastion
  gather_facts: False
  roles:
    - monitor_cluster
  vars:
    - debug: True
    - ASSISTED_INSTALLER_HOST: "{{ hostvars['assisted_installer']['host'] }}"
    - ASSISTED_INSTALLER_PORT: "{{ hostvars['assisted_installer']['port'] }}"
    - CLUSTER_ID: "{{ cluster_id }}"
