
- name: check skopeo is installed
  shell: /usr/bin/skopeo --version

- name: Find hash for images
  include_tasks:
    file: get_image_hash.yml
    apply:
      tags:
        - install
  loop: "{{ images_to_get_hash_for | dict2items }}"
