---
# tasks file for generate_discovery_iso

- name: create a default config
  set_fact:
    static_ips_config: []

- name : load the list of static IP addresses
  include_tasks: static.yml
  with_items:
    - "{{ groups['masters'] }}"
    - "{{ groups['workers'] | default([]) }}"

- name: Generate a new discovery ISO
  uri:
    url: "{{ URL_ASSISTED_INSTALLER_CLUSTERS_DOWNLOAD_IMAGE }}"
    method: POST
    url_username: "{{ HTTP_AUTH_USERNAME }}"
    url_password: "{{ HTTP_AUTH_PASSWORD }}"
    body_format: json
    status_code: [201]
    return_content: True
    body: { "ssh_public_key": "{{ ssh_public_key }}", "static_ips_config" : "{{ static_ips_config }}", "image_type": "full-iso" }
  when: generate | bool == True
  register: http_reply

- debug:
    var: http_reply.json
  when: debug and generate | bool == True

- name: Download discovery ISO
  get_url:
    url: "{{ URL_ASSISTED_INSTALLER_CLUSTERS_DOWNLOAD_IMAGE }}"
    dest: "{{ DOWNLOAD_DEST_PATH }}/{{ DOWNLOAD_DEST_FILE }}"
  when: download | bool == True
  register: http_reply

- debug:
    var: http_reply.status_code
  when: debug and download | bool == True

- name: Upload discovery ISO
  uri:
    url: "{{ URL_HTTP_STORE_UPLOAD_IMAGE }}/{{ CLUSTER_ID }}.iso"
    method: PUT
    url_username: "{{ HTTP_STORE_AUTH_USERNAME }}"
    url_password: "{{ HTTP_STORE_AUTH_PASSWORD }}"
    src: "{{ DOWNLOAD_DEST_PATH }}/{{ DOWNLOAD_DEST_FILE }}"
    status_code: [200]
  when: upload | bool == True
  register: http_reply

- debug:
    var: http_reply.status_code
  when: debug and upload | bool == True
