---
- name: DELL Power ON
  community.general.redfish_command:
    category: Systems
    command: PowerOn
    baseuri: "{{ hostvars[inventory_hostname]['bmc_address'] }}"
    username: "{{ hostvars[inventory_hostname]['bmc_user'] }}"
    password: "{{ hostvars[inventory_hostname]['bmc_password'] }}"

- block:
    - name: Set Dell OneTimeBoot VirtualCD (VCD-DVD)
      community.general.redfish_command:
        category: Systems
        command: SetOneTimeBoot
        bootdevice: VCD-DVD
        baseuri: "{{ hostvars[inventory_hostname]['bmc_address'] }}"
        username: "{{ hostvars[inventory_hostname]['bmc_user'] }}"
        password: "{{ hostvars[inventory_hostname]['bmc_password'] }}"
  rescue:
    - name: Set Dell OneTimeBoot VirtualCD (Cd)
      community.general.redfish_command:
        category: Systems
        command: SetOneTimeBoot
        bootdevice: Cd
        baseuri: "{{ hostvars[inventory_hostname]['bmc_address'] }}"
        username: "{{ hostvars[inventory_hostname]['bmc_user'] }}"
        password: "{{ hostvars[inventory_hostname]['bmc_password'] }}"

- name: DELL Eject Virtual Media (if any)
  community.general.redfish_command:
    category: Manager
    command: VirtualMediaEject
    baseuri: "{{ hostvars[inventory_hostname]['bmc_address'] }}"
    username: "{{ hostvars[inventory_hostname]['bmc_user'] }}"
    password: "{{ hostvars[inventory_hostname]['bmc_password'] }}"
    virtual_media:
      image_url: "{{ boot_iso_url }}"
    resource_id: iDRAC.Embedded.1
  ignore_errors: yes

- name: DELL Insert Virtual Media
  community.general.redfish_command:
    category: Manager
    command: VirtualMediaInsert
    baseuri: "{{ hostvars[inventory_hostname]['bmc_address'] }}"
    username: "{{ hostvars[inventory_hostname]['bmc_user'] }}"
    password: "{{ hostvars[inventory_hostname]['bmc_password'] }}"
    virtual_media:
      image_url: "{{ boot_iso_url }}"
      media_types:
      - CD
      - DVD
    resource_id: iDRAC.Embedded.1

- name: DELL Restart system power gracefully
  community.general.redfish_command:
    category: Systems
    command: PowerGracefulRestart
    baseuri: "{{ hostvars[inventory_hostname]['bmc_address'] }}"
    username: "{{ hostvars[inventory_hostname]['bmc_user'] }}"
    password: "{{ hostvars[inventory_hostname]['bmc_password'] }}"
